[server]
host = "localhost"
port = 8080

[database]
driver = "mysql"
source = "root:passw0rd@tcp(localhost:3306)/mall"

[redis]
addr = "localhost:6379"
password = ""
db = 0

[elasticsearch]
addresses = ["http://localhost:9200"]
api_key = "ZWF4WDM1UUIxbWFmQVM1d0d6dDg6V290Q21saG1Rb3k3d1V2am5aaWVhQQ=="
indices = "mall"

[services]
admin_service = "localhost:50010"
order_service = "localhost:50020"