// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"google.golang.org/grpc"
	"mall/app/user/internal/config"
	"mall/app/user/internal/data"
	"mall/app/user/internal/server"
	"mall/app/user/internal/service"
)

// Injectors from wire.go:

func wireApp() (*grpc.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	dataData, err := data.NewData(configConfig)
	if err != nil {
		return nil, err
	}
	cartRepo := data.NewCartRepo(dataData)
	cartService := service.NewCartService(cartRepo)
	grpcServer := server.NewGRPCServer(cartService)
	return grpcServer, nil
}
