// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"google.golang.org/grpc"
	"mall/app/callback/internal/config"
	"mall/app/callback/internal/data"
	"mall/app/callback/internal/server"
	"mall/app/callback/internal/service"
)

// Injectors from wire.go:

func wireApp() (*grpc.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	dataData, err := data.NewData(configConfig)
	if err != nil {
		return nil, err
	}
	paymentRepo := data.NewPaymentRepo(dataData)
	callbackService := service.NewCallbackService(paymentRepo)
	grpcServer := server.NewGRPCServer(callbackService)
	return grpcServer, nil
}
