// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"google.golang.org/grpc"
	"mall/app/auth/internal/config"
	"mall/app/auth/internal/data"
	"mall/app/auth/internal/server"
	"mall/app/auth/internal/service"
)

// Injectors from wire.go:

func wireApp() (*grpc.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	dataData, err := data.NewData(configConfig)
	if err != nil {
		return nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	passwordRepo := data.NewPasswordRepo(dataData)
	userService := service.NewUserService(userRepo, passwordRepo)
	grpcServer := server.NewGRPCServer(userService)
	return grpcServer, nil
}
