// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"google.golang.org/grpc"
	"mall/app/admin/internal/config"
	"mall/app/admin/internal/data"
	"mall/app/admin/internal/server"
	"mall/app/admin/internal/service"
)

// Injectors from wire.go:

func wireApp() (*grpc.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	dataData, err := data.NewData(configConfig)
	if err != nil {
		return nil, err
	}
	itemRepo := data.NewItemRepo(dataData)
	itemService := service.NewItemService(itemRepo)
	grpcServer := server.NewGRPCServer(itemService)
	return grpcServer, nil
}
