// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mall/ent/cartitem"
	"mall/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cartitemFields := schema.CartItem{}.Fields()
	_ = cartitemFields
	// cartitemDescQuantity is the schema descriptor for quantity field.
	cartitemDescQuantity := cartitemFields[0].Descriptor()
	// cartitem.DefaultQuantity holds the default value on creation for the quantity field.
	cartitem.DefaultQuantity = cartitemDescQuantity.Default.(int)
	// cartitem.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	cartitem.QuantityValidator = cartitemDescQuantity.Validators[0].(func(int) error)
}
