// Code generated by ent, DO NOT EDIT.

package ent

import (
	"mall/ent/cartitem"
	"mall/ent/orderitem"
	"mall/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cartitemFields := schema.CartItem{}.Fields()
	_ = cartitemFields
	// cartitemDescQuantity is the schema descriptor for quantity field.
	cartitemDescQuantity := cartitemFields[0].Descriptor()
	// cartitem.DefaultQuantity holds the default value on creation for the quantity field.
	cartitem.DefaultQuantity = cartitemDescQuantity.Default.(int)
	// cartitem.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	cartitem.QuantityValidator = cartitemDescQuantity.Validators[0].(func(int) error)
	orderitemFields := schema.OrderItem{}.Fields()
	_ = orderitemFields
	// orderitemDescQuantity is the schema descriptor for quantity field.
	orderitemDescQuantity := orderitemFields[0].Descriptor()
	// orderitem.DefaultQuantity holds the default value on creation for the quantity field.
	orderitem.DefaultQuantity = orderitemDescQuantity.Default.(int)
	// orderitem.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	orderitem.QuantityValidator = orderitemDescQuantity.Validators[0].(func(int) error)
	// orderitemDescPrice is the schema descriptor for price field.
	orderitemDescPrice := orderitemFields[1].Descriptor()
	// orderitem.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	orderitem.PriceValidator = orderitemDescPrice.Validators[0].(func(float32) error)
}
