// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"google.golang.org/grpc"
	"mall/app/gateway/internal/config"
	"mall/app/gateway/internal/data"
	"mall/app/gateway/internal/server"
	"mall/app/gateway/internal/service"
)

// Injectors from wire.go:

func wireApp() (*grpc.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	dataData, err := data.NewData(configConfig)
	if err != nil {
		return nil, err
	}
	cartService := service.NewCartService(dataData)
	itemService := service.NewItemService(dataData)
	orderService := service.NewOrderService(dataData)
	paymentService := service.NewPaymentService(dataData)
	userRepo := data.NewUserRepo(dataData)
	passwordRepo := data.NewPasswordRepo(dataData)
	userService := service.NewUserService(userRepo, passwordRepo)
	grpcServer := server.NewGRPCServer(cartService, itemService, orderService, paymentService, userService)
	return grpcServer, nil
}
