// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"google.golang.org/grpc"
	"mall/app/payment/internal/config"
	"mall/app/payment/internal/data"
	"mall/app/payment/internal/server"
	"mall/app/payment/internal/service"
)

// Injectors from wire.go:

func wireApp() (*grpc.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	dataData, err := data.NewData(configConfig)
	if err != nil {
		return nil, err
	}
	paymentRepo := data.NewPaymentRepo(dataData)
	paymentService := service.NewPaymentService(paymentRepo)
	grpcServer := server.NewGRPCServer(configConfig, paymentService)
	return grpcServer, nil
}
