// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"google.golang.org/grpc"
	"mall/app/order/internal/config"
	"mall/app/order/internal/data"
	"mall/app/order/internal/server"
	"mall/app/order/internal/service"
)

// Injectors from wire.go:

func wireApp() (*grpc.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	dataData, err := data.NewData(configConfig)
	if err != nil {
		return nil, err
	}
	orderRepo := data.NewOrderRepo(dataData)
	orderService := service.NewOrderService(orderRepo)
	grpcServer := server.NewGRPCServer(configConfig, orderService)
	return grpcServer, nil
}
