apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-user
spec:
  replicas: 1  # 设置 Pod 的副本数
  selector:
    matchLabels:
      app: mall-user
  template:
    metadata:
      labels:
        app: mall-user
    spec:
      containers:
        - name: mall-user
          image: user-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50040  # gRPC 服务的端口